# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0fa90b5573c67e06ea6a9966a2539057039e131118a4c6a1e8c2f666eca02a289266e773df2819175ee7ed798cd6d965e1ddd83cf0ff7284ad3490f8b430c2d9

test:
  secret_key_base: 13105651c4fc677f28df0040a8c0568e831c1a34ee46ccc90fd396c751367b33c8a4c8b451eb4a30e7f57a0e55cb1cb8460b18f3d021251dd4417ff92a334186

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
