class CreatePis < ActiveRecord::Migration[5.1]
  def change
    create_table :pis do |t|
        t.double :"sender"
        t.double :"Openness"
        t.double :"Adventurousness"
        t.double :"Artistic interests"
        t.double :"Emotionality"
        t.double :"Imagination"
        t.double :"Intellect"
        t.double :"Authority-challenging"
        t.double :"Conscientiousness"
        t.double :"Achievement striving"
        t.double :"Cautiousness"
        t.double :"Dutifulness"
        t.double :"Orderliness"
        t.double :"Self-discipline"
        t.double :"Self-efficacy"
        t.double :"Extraversion"
        t.double :"Activity level"
        t.double :"Assertiveness"
        t.double :"Cheerfulness"
        t.double :"Excitement-seeking"
        t.double :"Outgoing"
        t.double :"Gregariousness"
        t.double :"Agreeableness"
        t.double :"Altruism"
        t.double :"Cooperation"
        t.double :"Modesty"
        t.double :"Uncompromising"
        t.double :"Sympathy"
        t.double :"Trust"
        t.double :"Emotional range"
        t.double :"Fiery"
        t.double :"Prone to worry"
        t.double :"Melancholy"
        t.double :"Immoderation"
        t.double :"Self-consciousness"
        t.double :"Susceptible to stress"
      t.timestamps
    end
  end
end
